export const theme = {
  colors: {
    background: "#F7F7F5",
    surface: "#FFFFFF",
    primary: "#2F6F4F",
    primaryMuted: "#E8F1EC",
    primaryText: "#FFFFFF",
    danger: "#B3261E",
    dangerMuted: "#FDECEA",
    dangerFill: "rgba(179, 38, 30, 0.1)",
    primaryFill: "rgba(47, 111, 79, 0.12)",
    textPrimary: "#1A1A1A",
    textSecondary: "#6B6B6B",
    textMuted: "#9B9B95",
    border: "#E5E5E1",
    inputBg: "#F7F7F5",
    overlay: "rgba(0, 0, 0, 0.45)",
    pressed: "#FAFAF8",
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    pill: 999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
  },
  shadow: {
    card: {
      shadowColor: "#1A1A1A",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.06,
      shadowRadius: 12,
      elevation: 3,
    },
    floating: {
      shadowColor: "#1A1A1A",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.1,
      shadowRadius: 20,
      elevation: 6,
    },
  },
  animation: {
    fast: 150,
    normal: 250,
    slow: 400,
  },
} as const;
